const errorCodes = {
  JOIN_GAME_DUPLICATION: 'JG-0010',
  JOIN_GAME_STARTED: 'JG-0020',
  JOIN_GAME_OVER_4: 'JG-0030',
  CREATE_RECORD_GAME_NOT_EXIST: 'CR-0010',
  CREATE_RECORD_GAME_COMPLETED: 'CR-0020',
}
export default errorCodes
